# Generated by Django 4.2.7 on 2026-04-25 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movielist',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='in_lists', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='movielist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
