# Generated by Django 4.2.7 on 2026-04-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMovieExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.BooleanField(default=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('feeling', models.TextField(blank=True)),
                ('mood_tag', models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('excited', 'Excited'), ('scared', 'Scared'), ('emotional', 'Emotional'), ('mind-blowing', 'Mind-Blowing'), ('bored', 'Bored'), ('inspired', 'Inspired'), ('romantic', 'Romantic'), ('tense', 'Tense'), ('nostalgic', 'Nostalgic'), ('confused', 'Confused'), ('amused', 'Amused')], max_length=50)),
                ('rewatch', models.BooleanField(default=False)),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
