# Generated by Django 4.2.7 on 2026-04-25 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experience', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovieexperience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usermovieexperience',
            unique_together={('user', 'movie')},
        ),
    ]
