# Generated by Django 4.2.7 on 2026-04-25 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('original_title', models.CharField(blank=True, max_length=500)),
                ('overview', models.TextField(blank=True)),
                ('genre_names', models.CharField(blank=True, max_length=500)),
                ('tmdb_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('imdb_id', models.CharField(blank=True, db_index=True, max_length=20)),
                ('release_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=20)),
                ('source', models.CharField(choices=[('tmdb', 'TMDB'), ('indian', 'Indian')], db_index=True, default='tmdb', max_length=20)),
                ('rating', models.FloatField(blank=True, db_index=True, null=True)),
                ('vote_count', models.IntegerField(default=0)),
                ('popularity', models.FloatField(db_index=True, default=0.0)),
                ('poster_url', models.URLField(blank=True, max_length=1000)),
                ('poster_fetched', models.BooleanField(default=False)),
                ('feature_vector', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-popularity', '-rating'],
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlisted_by', to='movies.movie')),
            ],
        ),
    ]
